package com.zeus.entity;

import java.util.Date;
/**
 *
 *
 * @methodName   物品
 * @author wangdi
 * @param
 * @return
 * @date 2019/1/10
 */
public class ActivityUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user.id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user.title
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user.small_pic
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    private String smallPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user.user_id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user.create_time
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user.status
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user.activity_product_id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    private Long activityProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user.article_id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    private Long articleId;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user.id
     *
     * @return the value of activity_user.id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user.id
     *
     * @param id the value for activity_user.id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user.title
     *
     * @return the value of activity_user.title
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user.title
     *
     * @param title the value for activity_user.title
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user.small_pic
     *
     * @return the value of activity_user.small_pic
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public String getSmallPic() {
        return smallPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user.small_pic
     *
     * @param smallPic the value for activity_user.small_pic
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public void setSmallPic(String smallPic) {
        this.smallPic = smallPic == null ? null : smallPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user.user_id
     *
     * @return the value of activity_user.user_id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user.user_id
     *
     * @param userId the value for activity_user.user_id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user.create_time
     *
     * @return the value of activity_user.create_time
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user.create_time
     *
     * @param createTime the value for activity_user.create_time
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user.status
     *
     * @return the value of activity_user.status
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user.status
     *
     * @param status the value for activity_user.status
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user.activity_product_id
     *
     * @return the value of activity_user.activity_product_id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public Long getActivityProductId() {
        return activityProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user.activity_product_id
     *
     * @param activityProductId the value for activity_user.activity_product_id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public void setActivityProductId(Long activityProductId) {
        this.activityProductId = activityProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user.article_id
     *
     * @return the value of activity_user.article_id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user.article_id
     *
     * @param articleId the value for activity_user.article_id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }
}