package com.zeus.entity;

import java.util.Date;
/**
 * @Description 回收袋实体类
 * @author:wangdi
 * @date:2019/1/7
 * @ver:1.0
 */
public class Bags {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bags.id
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bags.user_id
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bags.serial_number
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    private Long serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bags.recycle_bin_serial_number
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    private Long recycleBinSerialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bags.create_time
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bags.update_time
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bags.status
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bags.bagsType
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    private String bagstype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bags.recycle_bin_id
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    private Long recycleBinId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bags.orc_id
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    private Long orcId;




    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bags.id
     *
     * @return the value of bags.id
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bags.id
     *
     * @param id the value for bags.id
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bags.user_id
     *
     * @return the value of bags.user_id
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bags.user_id
     *
     * @param userId the value for bags.user_id
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bags.serial_number
     *
     * @return the value of bags.serial_number
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    public Long getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bags.serial_number
     *
     * @param serialNumber the value for bags.serial_number
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    public void setSerialNumber(Long serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bags.recycle_bin_serial_number
     *
     * @return the value of bags.recycle_bin_serial_number
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    public Long getRecycleBinSerialNumber() {
        return recycleBinSerialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bags.recycle_bin_serial_number
     *
     * @param recycleBinSerialNumber the value for bags.recycle_bin_serial_number
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    public void setRecycleBinSerialNumber(Long recycleBinSerialNumber) {
        this.recycleBinSerialNumber = recycleBinSerialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bags.create_time
     *
     * @return the value of bags.create_time
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bags.create_time
     *
     * @param createTime the value for bags.create_time
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bags.update_time
     *
     * @return the value of bags.update_time
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bags.update_time
     *
     * @param updateTime the value for bags.update_time
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bags.status
     *
     * @return the value of bags.status
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bags.status
     *
     * @param status the value for bags.status
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bags.bagsType
     *
     * @return the value of bags.bagsType
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    public String getBagstype() {
        return bagstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bags.bagsType
     *
     * @param bagstype the value for bags.bagsType
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    public void setBagstype(String bagstype) {
        this.bagstype = bagstype == null ? null : bagstype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bags.recycle_bin_id
     *
     * @return the value of bags.recycle_bin_id
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    public Long getRecycleBinId() {
        return recycleBinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bags.recycle_bin_id
     *
     * @param recycleBinId the value for bags.recycle_bin_id
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    public void setRecycleBinId(Long recycleBinId) {
        this.recycleBinId = recycleBinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bags.orc_id
     *
     * @return the value of bags.orc_id
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    public Long getOrcId() {
        return orcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bags.orc_id
     *
     * @param orcId the value for bags.orc_id
     *
     * @mbggenerated Wed Jan 16 14:47:00 CST 2019
     */
    public void setOrcId(Long orcId) {
        this.orcId = orcId;
    }
}