package com.zeus.entity;

import java.util.Date;
/**
 *
 *
 * @methodName  评论用户
 * @author wangdi
 * @param
 * @return
 * @date 2019/1/10
 */
public class CommentsUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments_user.id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments_user.small_pic
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    private String smallPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments_user.user_id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments_user.create_time
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments_user.status
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments_user.comments
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments_user.activity_product_id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    private Long activityProductId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments_user.id
     *
     * @return the value of comments_user.id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments_user.id
     *
     * @param id the value for comments_user.id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments_user.small_pic
     *
     * @return the value of comments_user.small_pic
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public String getSmallPic() {
        return smallPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments_user.small_pic
     *
     * @param smallPic the value for comments_user.small_pic
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public void setSmallPic(String smallPic) {
        this.smallPic = smallPic == null ? null : smallPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments_user.user_id
     *
     * @return the value of comments_user.user_id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments_user.user_id
     *
     * @param userId the value for comments_user.user_id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments_user.create_time
     *
     * @return the value of comments_user.create_time
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments_user.create_time
     *
     * @param createTime the value for comments_user.create_time
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments_user.status
     *
     * @return the value of comments_user.status
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments_user.status
     *
     * @param status the value for comments_user.status
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments_user.comments
     *
     * @return the value of comments_user.comments
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments_user.comments
     *
     * @param comments the value for comments_user.comments
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments_user.activity_product_id
     *
     * @return the value of comments_user.activity_product_id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public Long getActivityProductId() {
        return activityProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments_user.activity_product_id
     *
     * @param activityProductId the value for comments_user.activity_product_id
     *
     * @mbggenerated Wed Jan 09 16:07:36 CST 2019
     */
    public void setActivityProductId(Long activityProductId) {
        this.activityProductId = activityProductId;
    }
}