package com.zeus.entity;
/**
 * @Description 回收站实体类
 * @author:wangdi
 * @date:2019/1/7
 * @ver:1.0
 */
public class Recycle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recycle.id
     *
     * @mbggenerated Fri Jan 18 09:46:05 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recycle.sitenum
     *
     * @mbggenerated Fri Jan 18 09:46:05 CST 2019
     */
    private Long sitenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recycle.cell_name
     *
     * @mbggenerated Fri Jan 18 09:46:05 CST 2019
     */
    private String cellName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recycle.id
     *
     * @return the value of recycle.id
     *
     * @mbggenerated Fri Jan 18 09:46:05 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recycle.id
     *
     * @param id the value for recycle.id
     *
     * @mbggenerated Fri Jan 18 09:46:05 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recycle.sitenum
     *
     * @return the value of recycle.sitenum
     *
     * @mbggenerated Fri Jan 18 09:46:05 CST 2019
     */
    public Long getSitenum() {
        return sitenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recycle.sitenum
     *
     * @param sitenum the value for recycle.sitenum
     *
     * @mbggenerated Fri Jan 18 09:46:05 CST 2019
     */
    public void setSitenum(Long sitenum) {
        this.sitenum = sitenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recycle.cell_name
     *
     * @return the value of recycle.cell_name
     *
     * @mbggenerated Fri Jan 18 09:46:05 CST 2019
     */
    public String getCellName() {
        return cellName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recycle.cell_name
     *
     * @param cellName the value for recycle.cell_name
     *
     * @mbggenerated Fri Jan 18 09:46:05 CST 2019
     */
    public void setCellName(String cellName) {
        this.cellName = cellName == null ? null : cellName.trim();
    }
}