package com.zeus.entity;

public class WorkUsersRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_users_role.userId
     *
     * @mbggenerated Mon Jan 28 18:19:10 CST 2019
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_users_role.roleId
     *
     * @mbggenerated Mon Jan 28 18:19:10 CST 2019
     */
    private Long roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_users_role.userId
     *
     * @return the value of work_users_role.userId
     *
     * @mbggenerated Mon Jan 28 18:19:10 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_users_role.userId
     *
     * @param userid the value for work_users_role.userId
     *
     * @mbggenerated Mon Jan 28 18:19:10 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_users_role.roleId
     *
     * @return the value of work_users_role.roleId
     *
     * @mbggenerated Mon Jan 28 18:19:10 CST 2019
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_users_role.roleId
     *
     * @param roleid the value for work_users_role.roleId
     *
     * @mbggenerated Mon Jan 28 18:19:10 CST 2019
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }
}