package com.zeus.entity;

import java.util.Date;
/**
 * @Description
 * @Author wangdi
 * @Date 1/3/2019 23:30
 * @Version V1.0
 */
public class ArticleStdmode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_stdmode.id
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_stdmode.small_pic
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    private String smallPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_stdmode.create_time
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_stdmode.status
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_stdmode.article_name
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    private String articleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_stdmode.article_weight
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    private Double articleWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_stdmode.update_time
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_stdmode.article_price
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    private Double articlePrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_stdmode.id
     *
     * @return the value of article_stdmode.id
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_stdmode.id
     *
     * @param id the value for article_stdmode.id
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_stdmode.small_pic
     *
     * @return the value of article_stdmode.small_pic
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    public String getSmallPic() {
        return smallPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_stdmode.small_pic
     *
     * @param smallPic the value for article_stdmode.small_pic
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    public void setSmallPic(String smallPic) {
        this.smallPic = smallPic == null ? null : smallPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_stdmode.create_time
     *
     * @return the value of article_stdmode.create_time
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_stdmode.create_time
     *
     * @param createTime the value for article_stdmode.create_time
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_stdmode.status
     *
     * @return the value of article_stdmode.status
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_stdmode.status
     *
     * @param status the value for article_stdmode.status
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_stdmode.article_name
     *
     * @return the value of article_stdmode.article_name
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    public String getArticleName() {
        return articleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_stdmode.article_name
     *
     * @param articleName the value for article_stdmode.article_name
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    public void setArticleName(String articleName) {
        this.articleName = articleName == null ? null : articleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_stdmode.article_weight
     *
     * @return the value of article_stdmode.article_weight
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    public Double getArticleWeight() {
        return articleWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_stdmode.article_weight
     *
     * @param articleWeight the value for article_stdmode.article_weight
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    public void setArticleWeight(Double articleWeight) {
        this.articleWeight = articleWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_stdmode.update_time
     *
     * @return the value of article_stdmode.update_time
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_stdmode.update_time
     *
     * @param updateTime the value for article_stdmode.update_time
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_stdmode.article_price
     *
     * @return the value of article_stdmode.article_price
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    public Double getArticlePrice() {
        return articlePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_stdmode.article_price
     *
     * @param articlePrice the value for article_stdmode.article_price
     *
     * @mbggenerated Fri Jan 18 10:28:21 CST 2019
     */
    public void setArticlePrice(Double articlePrice) {
        this.articlePrice = articlePrice;
    }
}