package com.zeus.entity;

import java.util.Date;
/**
 * @Description
 * @Author wangdi
 * @Date 1/3/2019 23:30
 * @Version V1.0
 */
public class Carousel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.id
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.title
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.small_pic
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    private String smallPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.seller_id
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    private String sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.create_time
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.introduction
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.coupon_id
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    private Long couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.activity_product_id
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    private Long activityProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.status
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.id
     *
     * @return the value of carousel.id
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.id
     *
     * @param id the value for carousel.id
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.title
     *
     * @return the value of carousel.title
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.title
     *
     * @param title the value for carousel.title
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.small_pic
     *
     * @return the value of carousel.small_pic
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    public String getSmallPic() {
        return smallPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.small_pic
     *
     * @param smallPic the value for carousel.small_pic
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    public void setSmallPic(String smallPic) {
        this.smallPic = smallPic == null ? null : smallPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.seller_id
     *
     * @return the value of carousel.seller_id
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.seller_id
     *
     * @param sellerId the value for carousel.seller_id
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId == null ? null : sellerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.create_time
     *
     * @return the value of carousel.create_time
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.create_time
     *
     * @param createTime the value for carousel.create_time
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.introduction
     *
     * @return the value of carousel.introduction
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.introduction
     *
     * @param introduction the value for carousel.introduction
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.coupon_id
     *
     * @return the value of carousel.coupon_id
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.coupon_id
     *
     * @param couponId the value for carousel.coupon_id
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.activity_product_id
     *
     * @return the value of carousel.activity_product_id
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    public Long getActivityProductId() {
        return activityProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.activity_product_id
     *
     * @param activityProductId the value for carousel.activity_product_id
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    public void setActivityProductId(Long activityProductId) {
        this.activityProductId = activityProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.status
     *
     * @return the value of carousel.status
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.status
     *
     * @param status the value for carousel.status
     *
     * @mbggenerated Mon Jan 21 12:37:07 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}