package com.zeus.entity;

import java.util.Date;
/**
 * @Description 回收箱实体类
 * @author:wangdi
 * @date:2019/1/7
 * @ver:1.0
 */
public class RecycleBin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recycle_bin.id
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recycle_bin.userId
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recycle_bin.serial_number
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    private Long serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recycle_bin.create_time
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recycle_bin.update_time
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recycle_bin.bagsNum
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    private Long bagsnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recycle_bin.recycle_site_name
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    private String recycleSiteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recycle_bin.status
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recycle_bin.orc_id
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    private Long orcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recycle_bin.recycle_site_id
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    private Long recycleSiteId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recycle_bin.id
     *
     * @return the value of recycle_bin.id
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recycle_bin.id
     *
     * @param id the value for recycle_bin.id
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recycle_bin.userId
     *
     * @return the value of recycle_bin.userId
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recycle_bin.userId
     *
     * @param userid the value for recycle_bin.userId
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recycle_bin.serial_number
     *
     * @return the value of recycle_bin.serial_number
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    public Long getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recycle_bin.serial_number
     *
     * @param serialNumber the value for recycle_bin.serial_number
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    public void setSerialNumber(Long serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recycle_bin.create_time
     *
     * @return the value of recycle_bin.create_time
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recycle_bin.create_time
     *
     * @param createTime the value for recycle_bin.create_time
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recycle_bin.update_time
     *
     * @return the value of recycle_bin.update_time
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recycle_bin.update_time
     *
     * @param updateTime the value for recycle_bin.update_time
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recycle_bin.bagsNum
     *
     * @return the value of recycle_bin.bagsNum
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    public Long getBagsnum() {
        return bagsnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recycle_bin.bagsNum
     *
     * @param bagsnum the value for recycle_bin.bagsNum
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    public void setBagsnum(Long bagsnum) {
        this.bagsnum = bagsnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recycle_bin.recycle_site_name
     *
     * @return the value of recycle_bin.recycle_site_name
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    public String getRecycleSiteName() {
        return recycleSiteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recycle_bin.recycle_site_name
     *
     * @param recycleSiteName the value for recycle_bin.recycle_site_name
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    public void setRecycleSiteName(String recycleSiteName) {
        this.recycleSiteName = recycleSiteName == null ? null : recycleSiteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recycle_bin.status
     *
     * @return the value of recycle_bin.status
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recycle_bin.status
     *
     * @param status the value for recycle_bin.status
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recycle_bin.orc_id
     *
     * @return the value of recycle_bin.orc_id
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    public Long getOrcId() {
        return orcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recycle_bin.orc_id
     *
     * @param orcId the value for recycle_bin.orc_id
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    public void setOrcId(Long orcId) {
        this.orcId = orcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recycle_bin.recycle_site_id
     *
     * @return the value of recycle_bin.recycle_site_id
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    public Long getRecycleSiteId() {
        return recycleSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recycle_bin.recycle_site_id
     *
     * @param recycleSiteId the value for recycle_bin.recycle_site_id
     *
     * @mbggenerated Thu Jan 17 15:35:49 CST 2019
     */
    public void setRecycleSiteId(Long recycleSiteId) {
        this.recycleSiteId = recycleSiteId;
    }
}