package com.zeus.entity;

import java.util.Date;

/**
 * @Description 账户
 * @Author wangdi
 * @Date 1/7/2019 23:30
 * @Version V1.0
 */
public class EcsAccountLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_account_log.log_id
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    private Long logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_account_log.user_id
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_account_log.user_money
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    private Double userMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_account_log.frozen_money
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    private Double frozenMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_account_log.rank_points
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    private Integer rankPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_account_log.pay_points
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    private Integer payPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_account_log.change_time
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    private Date changeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_account_log.change_desc
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    private String changeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_account_log.change_type
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    private String changeType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_account_log.log_id
     *
     * @return the value of ecs_account_log.log_id
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_account_log.log_id
     *
     * @param logId the value for ecs_account_log.log_id
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_account_log.user_id
     *
     * @return the value of ecs_account_log.user_id
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_account_log.user_id
     *
     * @param userId the value for ecs_account_log.user_id
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_account_log.user_money
     *
     * @return the value of ecs_account_log.user_money
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    public Double getUserMoney() {
        return userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_account_log.user_money
     *
     * @param userMoney the value for ecs_account_log.user_money
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    public void setUserMoney(Double userMoney) {
        this.userMoney = userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_account_log.frozen_money
     *
     * @return the value of ecs_account_log.frozen_money
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    public Double getFrozenMoney() {
        return frozenMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_account_log.frozen_money
     *
     * @param frozenMoney the value for ecs_account_log.frozen_money
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    public void setFrozenMoney(Double frozenMoney) {
        this.frozenMoney = frozenMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_account_log.rank_points
     *
     * @return the value of ecs_account_log.rank_points
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    public Integer getRankPoints() {
        return rankPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_account_log.rank_points
     *
     * @param rankPoints the value for ecs_account_log.rank_points
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    public void setRankPoints(Integer rankPoints) {
        this.rankPoints = rankPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_account_log.pay_points
     *
     * @return the value of ecs_account_log.pay_points
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    public Integer getPayPoints() {
        return payPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_account_log.pay_points
     *
     * @param payPoints the value for ecs_account_log.pay_points
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    public void setPayPoints(Integer payPoints) {
        this.payPoints = payPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_account_log.change_time
     *
     * @return the value of ecs_account_log.change_time
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_account_log.change_time
     *
     * @param changeTime the value for ecs_account_log.change_time
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_account_log.change_desc
     *
     * @return the value of ecs_account_log.change_desc
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    public String getChangeDesc() {
        return changeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_account_log.change_desc
     *
     * @param changeDesc the value for ecs_account_log.change_desc
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    public void setChangeDesc(String changeDesc) {
        this.changeDesc = changeDesc == null ? null : changeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_account_log.change_type
     *
     * @return the value of ecs_account_log.change_type
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    public String getChangeType() {
        return changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_account_log.change_type
     *
     * @param changeType the value for ecs_account_log.change_type
     *
     * @mbggenerated Tue Jan 15 14:41:28 CST 2019
     */
    public void setChangeType(String changeType) {
        this.changeType = changeType == null ? null : changeType.trim();
    }
}