package com.zeus.entity;

import java.util.Date;
/**
 * @Description 回收人员绑定仓库
 * @Author wangdi
 * @Date 1/13/2019 11:30
 * @Version V1.0
 */
public class RecycleUserNum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recycle_user_num.recycle_user_id
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    private Long recycleUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recycle_user_num.warehouse_id
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    private Long warehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recycle_user_num.create_time
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recycle_user_num.recycle_user_id
     *
     * @return the value of recycle_user_num.recycle_user_id
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public Long getRecycleUserId() {
        return recycleUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recycle_user_num.recycle_user_id
     *
     * @param recycleUserId the value for recycle_user_num.recycle_user_id
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public void setRecycleUserId(Long recycleUserId) {
        this.recycleUserId = recycleUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recycle_user_num.warehouse_id
     *
     * @return the value of recycle_user_num.warehouse_id
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public Long getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recycle_user_num.warehouse_id
     *
     * @param warehouseId the value for recycle_user_num.warehouse_id
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public void setWarehouseId(Long warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recycle_user_num.create_time
     *
     * @return the value of recycle_user_num.create_time
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recycle_user_num.create_time
     *
     * @param createTime the value for recycle_user_num.create_time
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}