package com.zeus.entity;

import java.util.Date;
/**
 * @Description 回收员和站点记录
 * @Author wangdi
 * @Date 1/13/2019 11:30
 * @Version V1.0
 */
public class SiteWorkUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_work_users.create_time
     *
     * @mbggenerated Sun Jan 27 18:23:31 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_work_users.site_id
     *
     * @mbggenerated Sun Jan 27 18:23:31 CST 2019
     */
    private Long siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_work_users.work_users
     *
     * @mbggenerated Sun Jan 27 18:23:31 CST 2019
     */
    private Long workUsers;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_work_users.create_time
     *
     * @return the value of site_work_users.create_time
     *
     * @mbggenerated Sun Jan 27 18:23:31 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_work_users.create_time
     *
     * @param createTime the value for site_work_users.create_time
     *
     * @mbggenerated Sun Jan 27 18:23:31 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_work_users.site_id
     *
     * @return the value of site_work_users.site_id
     *
     * @mbggenerated Sun Jan 27 18:23:31 CST 2019
     */
    public Long getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_work_users.site_id
     *
     * @param siteId the value for site_work_users.site_id
     *
     * @mbggenerated Sun Jan 27 18:23:31 CST 2019
     */
    public void setSiteId(Long siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_work_users.work_users
     *
     * @return the value of site_work_users.work_users
     *
     * @mbggenerated Sun Jan 27 18:23:31 CST 2019
     */
    public Long getWorkUsers() {
        return workUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_work_users.work_users
     *
     * @param workUsers the value for site_work_users.work_users
     *
     * @mbggenerated Sun Jan 27 18:23:31 CST 2019
     */
    public void setWorkUsers(Long workUsers) {
        this.workUsers = workUsers;
    }
}