package com.zeus.entity;

import java.util.Date;

public class Warehouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.id
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.warehouse_id
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    private Long warehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.serial_number
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    private Long serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.create_time
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.update_time
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.status
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.warehouse_name
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    private String warehouseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.orc_id
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    private Long orcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.bags_name
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    private Long bagsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.warehouse_article_id
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    private Long warehouseArticleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.id
     *
     * @return the value of warehouse.id
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.id
     *
     * @param id the value for warehouse.id
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.warehouse_id
     *
     * @return the value of warehouse.warehouse_id
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    public Long getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.warehouse_id
     *
     * @param warehouseId the value for warehouse.warehouse_id
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    public void setWarehouseId(Long warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.serial_number
     *
     * @return the value of warehouse.serial_number
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    public Long getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.serial_number
     *
     * @param serialNumber the value for warehouse.serial_number
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    public void setSerialNumber(Long serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.create_time
     *
     * @return the value of warehouse.create_time
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.create_time
     *
     * @param createTime the value for warehouse.create_time
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.update_time
     *
     * @return the value of warehouse.update_time
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.update_time
     *
     * @param updateTime the value for warehouse.update_time
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.status
     *
     * @return the value of warehouse.status
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.status
     *
     * @param status the value for warehouse.status
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.warehouse_name
     *
     * @return the value of warehouse.warehouse_name
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    public String getWarehouseName() {
        return warehouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.warehouse_name
     *
     * @param warehouseName the value for warehouse.warehouse_name
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName == null ? null : warehouseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.orc_id
     *
     * @return the value of warehouse.orc_id
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    public Long getOrcId() {
        return orcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.orc_id
     *
     * @param orcId the value for warehouse.orc_id
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    public void setOrcId(Long orcId) {
        this.orcId = orcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.bags_name
     *
     * @return the value of warehouse.bags_name
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    public Long getBagsName() {
        return bagsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.bags_name
     *
     * @param bagsName the value for warehouse.bags_name
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    public void setBagsName(Long bagsName) {
        this.bagsName = bagsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.warehouse_article_id
     *
     * @return the value of warehouse.warehouse_article_id
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    public Long getWarehouseArticleId() {
        return warehouseArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.warehouse_article_id
     *
     * @param warehouseArticleId the value for warehouse.warehouse_article_id
     *
     * @mbggenerated Fri Jan 18 10:39:15 CST 2019
     */
    public void setWarehouseArticleId(Long warehouseArticleId) {
        this.warehouseArticleId = warehouseArticleId;
    }
}