package com.zeus.entity;

import java.util.Date;

/**
 * @Description 仓库员录入物品的种类
 * @author:wangdi
 * @date:2019/1/7
 * @ver:1.0
 */
public class WarehouseArticle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_article.id
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_article.create_time
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_article.update_time
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_article.status
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_article.article_name
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    private String articleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_article.article_weight
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    private Double articleWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_article.article_price
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    private Double articlePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_article.price
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_article.id
     *
     * @return the value of warehouse_article.id
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_article.id
     *
     * @param id the value for warehouse_article.id
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_article.create_time
     *
     * @return the value of warehouse_article.create_time
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_article.create_time
     *
     * @param createTime the value for warehouse_article.create_time
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_article.update_time
     *
     * @return the value of warehouse_article.update_time
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_article.update_time
     *
     * @param updateTime the value for warehouse_article.update_time
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_article.status
     *
     * @return the value of warehouse_article.status
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_article.status
     *
     * @param status the value for warehouse_article.status
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_article.article_name
     *
     * @return the value of warehouse_article.article_name
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public String getArticleName() {
        return articleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_article.article_name
     *
     * @param articleName the value for warehouse_article.article_name
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public void setArticleName(String articleName) {
        this.articleName = articleName == null ? null : articleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_article.article_weight
     *
     * @return the value of warehouse_article.article_weight
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public Double getArticleWeight() {
        return articleWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_article.article_weight
     *
     * @param articleWeight the value for warehouse_article.article_weight
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public void setArticleWeight(Double articleWeight) {
        this.articleWeight = articleWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_article.article_price
     *
     * @return the value of warehouse_article.article_price
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public Double getArticlePrice() {
        return articlePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_article.article_price
     *
     * @param articlePrice the value for warehouse_article.article_price
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public void setArticlePrice(Double articlePrice) {
        this.articlePrice = articlePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_article.price
     *
     * @return the value of warehouse_article.price
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_article.price
     *
     * @param price the value for warehouse_article.price
     *
     * @mbggenerated Sat Jan 19 14:57:17 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}