package com.zeus.entity;

import java.util.Date;

public class WorkMoney {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_money.id
     *
     * @mbggenerated Sat Jan 19 18:41:31 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_money.create_time
     *
     * @mbggenerated Sat Jan 19 18:41:31 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_money.update_time
     *
     * @mbggenerated Sat Jan 19 18:41:31 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_money.status
     *
     * @mbggenerated Sat Jan 19 18:41:31 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_money.type
     *
     * @mbggenerated Sat Jan 19 18:41:31 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_money.money
     *
     * @mbggenerated Sat Jan 19 18:41:31 CST 2019
     */
    private Double money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_money.id
     *
     * @return the value of work_money.id
     *
     * @mbggenerated Sat Jan 19 18:41:31 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_money.id
     *
     * @param id the value for work_money.id
     *
     * @mbggenerated Sat Jan 19 18:41:31 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_money.create_time
     *
     * @return the value of work_money.create_time
     *
     * @mbggenerated Sat Jan 19 18:41:31 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_money.create_time
     *
     * @param createTime the value for work_money.create_time
     *
     * @mbggenerated Sat Jan 19 18:41:31 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_money.update_time
     *
     * @return the value of work_money.update_time
     *
     * @mbggenerated Sat Jan 19 18:41:31 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_money.update_time
     *
     * @param updateTime the value for work_money.update_time
     *
     * @mbggenerated Sat Jan 19 18:41:31 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_money.status
     *
     * @return the value of work_money.status
     *
     * @mbggenerated Sat Jan 19 18:41:31 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_money.status
     *
     * @param status the value for work_money.status
     *
     * @mbggenerated Sat Jan 19 18:41:31 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_money.type
     *
     * @return the value of work_money.type
     *
     * @mbggenerated Sat Jan 19 18:41:31 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_money.type
     *
     * @param type the value for work_money.type
     *
     * @mbggenerated Sat Jan 19 18:41:31 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_money.money
     *
     * @return the value of work_money.money
     *
     * @mbggenerated Sat Jan 19 18:41:31 CST 2019
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_money.money
     *
     * @param money the value for work_money.money
     *
     * @mbggenerated Sat Jan 19 18:41:31 CST 2019
     */
    public void setMoney(Double money) {
        this.money = money;
    }
}